/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package projeto_concessionaria.view;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import projeto_concessionaria.Model.Funcionario;
import projeto_concessionaria.controller.FuncionarioController;
import projeto_concessionaria.model.enums.CargoFuncionario;

/**
 *
 * @author Elise
 */
public class TelaLogin extends javax.swing.JPanel {
    private final JFrame framePai;
    private final FuncionarioController ControllerDoFuncionario = new FuncionarioController();
    
    public TelaLogin(JFrame framePai) {
        this.framePai = framePai;
        Funcionario Gab = new Funcionario("funcionario", "cpf do funcionario", "Telefone", "Email", CargoFuncionario.GERENTE, "funcionario", "senha");
        ControllerDoFuncionario.cadastrarFuncionario(Gab);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginInputContainer = new javax.swing.JPanel();
        InputLoginUser = new javax.swing.JTextField();
        SubmitLoginButton = new javax.swing.JButton();
        InputLoginPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Imagem = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(622, 613));
        setMinimumSize(new java.awt.Dimension(622, 613));
        setName(""); // NOI18N

        LoginInputContainer.setBackground(new java.awt.Color(0, 0, 0));

        InputLoginUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputLoginUserActionPerformed(evt);
            }
        });

        SubmitLoginButton.setText("Entrar");
        SubmitLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitLoginButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Senha");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Login");

        javax.swing.GroupLayout LoginInputContainerLayout = new javax.swing.GroupLayout(LoginInputContainer);
        LoginInputContainer.setLayout(LoginInputContainerLayout);
        LoginInputContainerLayout.setHorizontalGroup(
            LoginInputContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginInputContainerLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(LoginInputContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InputLoginUser, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(LoginInputContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginInputContainerLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(LoginInputContainerLayout.createSequentialGroup()
                        .addComponent(InputLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SubmitLoginButton)
                        .addGap(20, 20, 20))))
        );
        LoginInputContainerLayout.setVerticalGroup(
            LoginInputContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginInputContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LoginInputContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(LoginInputContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputLoginUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SubmitLoginButton)
                    .addComponent(InputLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        Imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Logo_Inicial(4).png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Imagem)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(LoginInputContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Imagem, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(LoginInputContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void InputLoginUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputLoginUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputLoginUserActionPerformed

    private void SubmitLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitLoginButtonActionPerformed
        String usuarioDigitado = InputLoginUser.getText();
        String senhaDigitada = new String(InputLoginPassword.getPassword());

        boolean loginValido = false;
        Funcionario funcionarioAutenticado = null;

        for (Funcionario f : ControllerDoFuncionario.listarFuncionarios()) {
            if (f.getLogin().equals(usuarioDigitado) && f.getSenha().equals(senhaDigitada)) {
                loginValido = true;
                funcionarioAutenticado = f;
                break;
            }
        }

        if (loginValido) {
            framePai.dispose();       
            TelaPrincipal principal = new TelaPrincipal(funcionarioAutenticado);
            principal.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Usuário ou senha incorretos!", "Erro de Login", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_SubmitLoginButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Imagem;
    private javax.swing.JPasswordField InputLoginPassword;
    private javax.swing.JTextField InputLoginUser;
    private javax.swing.JPanel LoginInputContainer;
    private javax.swing.JButton SubmitLoginButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
